package Skywars.Util;

public enum LanguageKeyword {
    ERR_NO_POSITION,
    ERR_NO_SPAWNPOINTS,
    ERR_NO_CHESTS,
    ERR_SAVING_UNSUCCESSFUL,
    ERR_WORLD_IN_CREATION,
    ERR_NO_WORLD_IN_CREATION,
    CMD_MAP_TRASHED
}
