main: Skywars.Main
version: 0.1
name: Skywars
authors: [JustFloooo, Nicronicson]
api-version: 1.13
commands:
  skywars complete map:
    description: Complete the creation of a map
    usage: /skywars complete map
    permission: skywars.command.create
  skywars create map:
    description: Create an Skywars map
    usage: /skywars create map
    permission: skywars.command.create
  skywars reset spawnpoints:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywars scan chests:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywars set pos1:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywars set pos2:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywars set spawn:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
permissions:
  skywars.command.create:
    default: op