main: Skywars.Main
version: 0.1
name: Skywars
authors: [JustFloooo, Nicronicson]
api-version: 1.13
commands:
  skywarscompletemap:
    description: Complete the creation of a map
    usage: /skywars complete map
    permission: skywars.command.create
  skywarscreatemap:
    description: Create an Skywars map
    usage: /skywarscreatemap
    permission: skywars.command.create
  skywarsresetspawnpoints:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywarsscanchests:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywarssetpos1:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywarssetpos2:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywarssetspawn:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywarstrashmap:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
  skywarssetmiddle:
    description: Change your speed
    usage: /s [speed]
    permission: skywars.command.create
permissions:
  skywars.command.create:
    default: op